language: generic
sudo: required
servides:
  - docker
 
before_install:
  - docker build -t rkdocker3191/react-test -f ./client/Dockerfile.dev ./client 
  
scripts:
  - docker run -e CI=true rkdocker3191/react-test npm test

after_success:
  - docker build -t rkdocker3191/multi-client ./client 
  - docker build -t rkdocker3191/multi-nginx ./nginx 
  - docker build -t rkdocker3191/multi-server ./server
  - docker build -t rkdocker3191/multi-worker ./worker   

  #docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  # take those images and push them to docker hub
  - docker push rkdocker3191/multi-client
  - docker push rkdocker3191/multi-nginx
  - docker push rkdocker3191/multi-server
  - docker push rkdocker3191/multi-worker  
       
deploy:
  edge: true      
  provider: elasticbeanstalk
  region: ap-south-1
  app: Multi-DockerEB
  env: MultiDockereb-env
  bucket_name: elasticbeanstalk-ap-south-1-627493753005
  bucket_path: docker-multi
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
